//! Plan Cascade Desktop - Rust Backend Library
//!
//! This library provides the core backend functionality for the Plan Cascade Desktop application.
//! It includes:
//! - Tauri command handlers for frontend IPC
//! - Business logic services
//! - Storage layer (SQLite, Keyring, Config)
//! - Data models and utilities

pub mod commands;
pub mod models;
pub mod services;
pub mod state;
pub mod storage;
pub mod utils;

// Re-export commonly used items from commands
pub use commands::{
    // Guardrail commands
    add_custom_rule,
    add_mcp_server,
    // Memory commands
    add_project_memory,
    aggregate_by_model,
    aggregate_by_project,
    artifact_delete,
    artifact_list,
    artifact_load,
    // Artifact commands
    artifact_save,
    artifact_versions,
    calculate_usage_cost,
    cancel_execution,
    cancel_standalone_execution,
    check_analytics_health,
    // Embedding configuration commands
    check_embedding_provider_health,
    check_provider_health,
    check_quality_gates_health,
    cleanup_gate_results,
    cleanup_standalone_sessions,
    clear_project_memories,
    clear_trigger_log,
    compile_spec,
    complete_worktree,
    configure_provider,
    // MCP commands
    connect_mcp_server,
    count_usage_records,
    create_agent,
    // Agent Composer commands
    create_agent_pipeline,
    // Timeline commands
    create_checkpoint,
    create_claude_md,
    create_evaluation_run,
    create_evaluator,
    create_graph_workflow,
    // Skill commands
    create_skill_file,
    create_webhook_channel,
    // Worktree commands
    create_worktree,
    delete_agent,
    delete_agent_pipeline,
    delete_branch,
    delete_checkpoint,
    delete_evaluation_run,
    delete_evaluator,
    delete_graph_workflow,
    delete_project_memory,
    delete_skill,
    delete_standalone_session,
    delete_usage_records,
    delete_webhook_channel,
    detect_applicable_skills,
    // Recovery commands
    detect_incomplete_tasks,
    // LSP commands
    detect_lsp_servers,
    detect_project_type_cmd,
    discard_task,
    disconnect_mcp_server,
    // A2A Remote Agent commands
    discover_a2a_agent,
    execute_standalone,
    // Session-based standalone commands
    execute_standalone_with_session,
    export_agents,
    export_by_model,
    export_by_project,
    export_pricing,
    export_time_series,
    export_usage,
    extract_session_memories,
    fetch_marketplace,
    fork_branch,
    // Design Document commands
    generate_design_doc,
    get_agent,
    get_agent_history,
    get_agent_pipeline,
    get_agent_run,
    get_agent_stats,
    get_available_gates,
    get_branch,
    get_checkpoint,
    get_checkpoint_diff,
    get_claude_md_metadata,
    get_dashboard_summary,
    get_default_gates_for_type,
    get_design_doc,
    get_diff_from_current,
    get_embedding_api_key,
    get_embedding_config,
    get_enrichment_report,
    get_evaluation_reports,
    get_gate_result,
    get_gate_results,
    get_graph_workflow,
    // Health commands
    get_health,
    get_interview_state,
    get_lsp_status,
    get_memory_stats,
    get_model_pricing,
    // Plugin commands
    get_plugin_detail,
    get_project,
    get_provider_api_key,
    get_session,
    get_session_gate_results,
    get_session_history,
    get_session_info,
    // Settings commands
    get_settings,
    get_skill,
    get_skills_overview,
    get_standalone_progress,
    get_standalone_session,
    get_standalone_status,
    get_summary_statistics,
    get_time_series,
    get_timeline,
    get_tracking_session,
    get_trigger_log,
    get_usage_statistics,
    get_usage_stats,
    get_version,
    get_webhook_deliveries,
    get_working_directory,
    get_worktree,
    get_worktree_status,
    git_amend_commit,
    git_check_llm_available,
    git_checkout_branch,
    git_commit,
    git_create_branch,
    git_delete_branch,
    git_diff_file,
    git_diff_staged,
    git_diff_unstaged,
    git_discard_changes,
    git_fetch,
    // Git Source Control commands
    git_full_status,
    git_generate_commit_message,
    git_get_conflict_files,
    git_get_merge_state,
    git_get_remotes,
    git_list_branches,
    git_list_remote_branches,
    git_list_stashes,
    git_log,
    git_log_graph,
    git_merge_abort,
    git_merge_branch,
    git_merge_continue,
    git_parse_file_conflicts,
    git_pull,
    git_push,
    git_read_file_content,
    git_rename_branch,
    git_resolve_conflict,
    git_resolve_conflict_ai,
    git_resolve_file_and_stage,
    git_review_diff,
    git_stage_files,
    git_stage_hunk,
    git_stash_drop,
    git_stash_pop,
    git_stash_save,
    git_summarize_commit,
    git_unstage_files,
    import_agents,
    import_design_doc,
    import_from_claude_desktop,
    init_analytics,
    // Init commands
    init_app,
    init_quality_gates,
    install_plugin,
    install_plugin_from_git,
    list_a2a_agents,
    list_active_sessions,
    list_agent_pipelines,
    // Agent commands
    list_agents,
    list_agents_with_stats,
    list_all_gates,
    list_branches,
    list_checkpoints,
    list_configured_api_key_providers,
    list_connected_mcp_servers,
    // Embedding configuration commands
    list_embedding_providers,
    list_evaluation_runs,
    // Evaluation commands
    list_evaluators,
    // Graph Workflow commands
    list_graph_workflows,
    list_guardrails,
    list_mcp_servers,
    list_mcp_tools,
    list_model_pricing,
    list_plugins,
    list_project_memories,
    // Project commands
    list_projects,
    // Standalone LLM commands
    list_providers,
    // Session commands
    list_sessions,
    list_skills,
    list_standalone_sessions,
    list_usage_records,
    // Webhook commands
    list_webhook_channels,
    list_worktrees,
    prune_agent_runs,
    rag_delete_collection,
    // Knowledge commands
    rag_ingest_documents,
    rag_list_collections,
    rag_query,
    read_claude_md,
    refresh_plugins,
    refresh_skill_index,
    register_a2a_agent,
    remove_a2a_agent,
    remove_custom_pricing,
    remove_custom_rule,
    remove_mcp_server,
    remove_session,
    remove_worktree,
    rename_branch,
    restore_checkpoint,
    resume_session,
    resume_standalone_execution,
    resume_task,
    retry_webhook_delivery,
    run_agent,
    run_custom_gates,
    run_quality_gates,
    run_specific_gates,
    save_claude_md,
    save_output_export,
    // Markdown commands
    scan_claude_md,
    search_project_memories,
    search_projects,
    search_sessions,
    search_skills,
    send_message,
    set_custom_pricing,
    set_embedding_api_key,
    set_embedding_config,
    set_tracking_session,
    set_working_directory,
    // Claude Code commands
    start_chat,
    start_spec_interview,
    submit_interview_answer,
    switch_branch,
    test_mcp_server,
    test_webhook_channel,
    toggle_generated_skill,
    toggle_guardrail,
    toggle_mcp_server,
    toggle_plugin,
    toggle_skill,
    track_usage,
    trigger_lsp_enrichment,
    uninstall_plugin,
    update_agent,
    update_agent_pipeline,
    update_graph_workflow,
    update_mcp_server,
    update_project_memory,
    update_settings,
    update_webhook_channel,
    // Analytics commands
    AnalyticsState,
    ArtifactState,
    ClaudeCodeState,
    GitState,
    GuardrailState,
    InitResult,
    KnowledgeState,
    LspState,
    // MCP runtime state
    McpRuntimeState,
    PluginState,
    // Quality Gates commands
    QualityGatesState,
    // Spec Interview commands
    SpecInterviewState,
    StandaloneState,
    WebhookState,
    WorktreeState,
};
// Re-export models (avoiding settings module conflict)
pub use models::response::*;
pub use models::settings::{AppConfig, SettingsUpdate};
pub use state::AppState;
pub use utils::error::{AppError, AppResult};
